    row A#5, 1, 00
    row A#4, 1, 00
    row F_5 , 1, 00
    row A#5, 1, 00
    row G#5, 1, 00
    row A#4, 1, 00
    row F_5 , 1, 00
    row G#5, 1, 00
    row G_5 , 1, 00
    row A#4, 1, 00
    row D#5, 1, 00
    row G_5 , 1, 00
    row G#5, 1, 00
    row A#4, 1, 00
    row F_5 , 1, 00
    row G#5, 1, 00
    row A#5, 1, 00
    row A#4, 1, 00
    row F_5 , 1, 00
    row A#5, 1, 00
    row G#5, 1, 00
    row A#4, 1, 00
    row F_5 , 1, 00
    row G#5, 1, 00
    row G_5 , 1, 00
    row A#4, 1, 00
    row D#5, 1, 00
    row G_5 , 1, 00
    row G#5, 1, 00
    row A#4, 1, 00
    row F_5 , 1, 00
    row G#5, 1, 00
    row A#5, 1, 00
    row A#4, 1, 00
    row F_5 , 1, 00
    row A#5, 1, 00
    row G#5, 1, 00
    row A#4, 1, 00
    row F_5 , 1, 00
    row G#5, 1, 00
    row G_5 , 1, 00
    row A#4, 1, 00
    row D#5, 1, 00
    row G_5 , 1, 00
    row G#5, 1, 00
    row A#4, 1, 00
    row F_5 , 1, 00
    row G#5, 1, 00
    row A#5, 1, 00
    row A#4, 1, 00
    row F_5 , 1, 00
    row A#5, 1, 00
    row G#5, 1, 00
    row A#4, 1, 00
    row F_5 , 1, 00
    row G#5, 1, 00
    row G_5 , 1, 00
    row A#4, 1, 00
    row D#5, 1, 00
    row G_5 , 1, 00
    row G#5, 1, 00
    row A#4, 1, 00
    row F_5 , 1, 00
    row G#5, 1, 00
