    row A#5, 00, 00
    row A#4, 00, 00
    row F_5 , 00, 00
    row A#5, 00, 00
    row G#5, 00, 00
    row A#4, 00, 00
    row F_5 , 00, 00
    row G#5, 00, 00
    row G_5 , 00, 00
    row A#4, 00, 00
    row D#5, 00, 00
    row G_5 , 00, 00
    row G#5, 00, 00
    row A#4, 00, 00
    row F_5 , 00, 00
    row G#5, 00, 00
    row A#5, 00, 00
    row A#4, 00, 00
    row F_5 , 00, 00
    row A#5, 00, 00
    row G#5, 00, 00
    row A#4, 00, 00
    row F_5 , 00, 00
    row G#5, 00, 00
    row G_5 , 00, 00
    row A#4, 00, 00
    row D#5, 00, 00
    row G_5 , 00, 00
    row G#5, 00, 00
    row A#4, 00, 00
    row F_5 , 00, 00
    row G#5, 00, 00
    row A#5, 00, 00
    row A#4, 00, 00
    row F_5 , 00, 00
    row A#5, 00, 00
    row G#5, 00, 00
    row A#4, 00, 00
    row F_5 , 00, 00
    row G#5, 00, 00
    row G_5 , 00, 00
    row A#4, 00, 00
    row D#5, 00, 00
    row G_5 , 00, 00
    row G#5, 00, 00
    row A#4, 00, 00
    row F_5 , 00, 00
    row G#5, 00, 00
    row A#5, 00, 00
    row A#4, 00, 00
    row F_5 , 00, 00
    row A#5, 00, 00
    row G#5, 00, 00
    row A#4, 00, 00
    row F_5 , 00, 00
    row G#5, 00, 00
    row G_5 , 00, 00
    row A#4, 00, 00
    row D#5, 00, 00
    row G_5 , 00, 00
    row G#5, 00, 00
    row A#4, 00, 00
    row F_5 , 00, 00
    row G#5, 00, 00
